# Generated by Django 5.2.10 on 2026-01-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_orderitemplate_orderplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplate',
            name='tatalArea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderplate',
            name='totalPerimeter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
