# Generated by Django 5.2.10 on 2026-01-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_orderplate_tatalarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemplate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_items', to='services.orderplate'),
        ),
    ]
