# Generated by Django 6.0.3 on 2026-03-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_orderitemplate_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.DecimalField(decimal_places=10, max_digits=20)),
                ('left', models.DecimalField(decimal_places=10, max_digits=20)),
                ('buttom', models.DecimalField(decimal_places=10, max_digits=20)),
                ('right', models.DecimalField(decimal_places=10, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orderplate',
            name='tatalArea',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderplate',
            name='totalPerimeter',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
