# Generated by Django 6.0.3 on 2026-03-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_drillingarea_alter_orderplate_tatalarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillingarea',
            name='buttom',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='drillingarea',
            name='left',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='drillingarea',
            name='right',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='drillingarea',
            name='top',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
